name: Run tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Print Java & Maven version
        run: |
          java -version
          mvn -version
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mvn -B -DskipTests clean install